version: '3'

services:

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommerce

  redis:
    image: redis:latest
